export const lightThemeVars = {
  headerBackgroundColor: '#00a69a',
  headerColor: 'black',
  mainBackgroundColor: 'white',
  cardTitleColor: 'black',
  cardMainColor: 'black',
  cardBackgroundColor: 'transperent',
  lightModeBackground: 'snow',
  lightModeColor: 'black',
  paginationButtonColor: '#00a69a',
  paginationButtonHoverColor: 'black',
  paginationButtonDisabledColor: 'gray',
  paginationButtonTextHoverColor: 'white',
  detailsColorText: 'black',
  goBackColor: 'black',
  popupVideoColor: 'white',
  picInPicbackground: 'white',
};

export const darkThemeVars = {
  headerBackgroundColor: '#2C3333',
  headerColor: '#0E8388',
  mainBackgroundColor: '#2E4F4F',
  cardTitleColor: 'white',
  cardMainColor: '#2C3333',
  cardBackgroundColor: '#2d4240',
  paginationButtonColor: '#2d4240',
  paginationButtonHoverColor: 'white',
  paginationButtonTextHoverColor: 'black',
  paginationButtonDisabledColor: 'gray',
  lightModeBackground: 'gold',
  lightModeColor: 'gold',
  detailsColorText: 'white',
  goBackColor: 'white',
  popupVideoColor: 'white',
  picInPicbackground: '#2C3333',
};
